Updated debian files

diff --git a/debian/bell-scheduler.postinst b/debian/bell-scheduler.postinst
--- a/debian/bell-scheduler.postinst
+++ b/debian/bell-scheduler.postinst
@@ -1,27 +1,31 @@
 #!/bin/sh
-# postrm script for lliurex-desktops-keeper
+# postinst script for bell-scheduler
 #
 # see: dh_installdeb(1)
 
 set -e
 
 # summary of how this script can be called:
-#        * <postrm> `remove'
-#        * <postrm> `purge'
-#        * <old-postrm> `upgrade' <new-version>
-#        * <new-postrm> `failed-upgrade' <old-version>
-#        * <new-postrm> `abort-install'
-#        * <new-postrm> `abort-install' <old-version>
-#        * <new-postrm> `abort-upgrade' <old-version>
-#        * <disappearer's-postrm> `disappear' <overwriter>
-#          <overwriter-version>
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
 # for details, see https://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
 
 case "$1" in
    	configure)
-    
+
+        newVersion=$(dpkg-query --showformat='${Version}' --show bell-scheduler)
+        tokenDir=/var/lib/bell-scheduler/version
+
+        echo "$newVersion" > "$tokenDir" || true
+
 		zero-center set-configured bell-scheduler-installer || true
 		
     ;;
